import type { Card } from '../types/card';

/**
 * DB の `cards.name` をキーに、表示用に上書きするフィールド。
 * Supabase の値より優先される。
 *
 * 内容は次のマイグレーション由来（手動編集せず `scripts/generate-card-info-overrides-from-sql.mjs` で再生成）:
 *   - 20260402140000_update_first_expansion_cards.sql
 *   - 20260402150000_update_second_expansion_cards.sql
 *   - 20260402160000_update_third_expansion_cards.sql
 *   - 20260402170000_update_fourth_expansion_cards.sql
 *
 * 画像は cardImageManifest.ts の CARD_IMAGE_MANIFEST を参照。
 */
export type CardInfoOverride = Partial<Omit<Card, 'id' | 'name'>>;

export const CARD_INFO_OVERRIDES: Record<string, CardInfoOverride> = {
    "エナジーボール": {
      effect_text: "・エナジーから1枚を選んで墓地に置きカードを2枚引く",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "メルト・パンチ": {
      effect_text: "・カウンター3\n・場にあるモンスター1体を破壊する",
      cost: 7,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "デカクラクション": {
      effect_text: "・カウンター2\n・手札を1枚捨てる。\n・場のコスト5以下のモンスターを1体選び破壊する。",
      cost: 6,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "墓起こし": {
      effect_text: "・自分の墓地のモンスターを1枚選び手札に加える。",
      cost: 5,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "電線復帰": {
      effect_text: "・自分の墓地のカードを1枚選びエナジー化させる。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "王家の宝箱": {
      effect_text: "・カウンター3\n・カードを3枚引く",
      cost: 6,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "セモタレエビ": {
      effect_text: "・登場時、山札の上から2枚を見る。そのあと山札の上と下にそれぞれ1枚ずつ戻す。",
      cost: 3,
      power: 1000,
      race: "海獣",
      card_type: "モンスター",
      is_unique: false,
    },
    "トンカチヘッド・シャーク": {
      effect_text: "・カウンター3\n・自分のモンスターがバトルに勝った時、このモンスターは手札に戻る。",
      cost: 5,
      power: 7000,
      race: "海獣",
      card_type: "モンスター",
      is_unique: false,
    },
    "大海覇者 メガロエンペラー": {
      effect_text: "・ツインアタッカー\n・登場時、次のうちどちらかを選ぶ。\n▶相手のモンスターを1体破壊する。\n▶相手の手札を2枚まで破壊する。\n・攻撃時、自分のエナジーを1枚選び手札に戻す。",
      cost: 9,
      power: 8000,
      race: "海獣/皇帝種",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "闇取り引きのディモン": {
      effect_text: "・登場時、場のカード1枚を破壊する。こうしてカードが破壊されたプレイヤーはカードを2枚まで引く。",
      cost: 6,
      power: 3000,
      race: "悪魔",
      card_type: "モンスター",
      is_unique: false,
    },
    "大空の使徒 デル・ローエ": {
      effect_text: "・登場時、自分は手札からカードを2枚を選び捨て、3枚引く。",
      cost: 8,
      power: 7000,
      race: "天使",
      card_type: "モンスター",
      is_unique: false,
    },
    "アルターナイツ ガーウィン": {
      effect_text: "・登場時、相手のパワー3000以下のモンスターを1体破壊する。",
      cost: 6,
      power: 4000,
      race: "ナイト",
      card_type: "モンスター",
      is_unique: false,
    },
    "アルターナイツ トリストラ": {
      effect_text: "・",
      cost: 8,
      power: 10000,
      race: "ナイト",
      card_type: "モンスター",
      is_unique: false,
    },
    "飛雷硬化 バリズム": {
      effect_text: "・フラッシュカウンター\n・ガードナー\n・登場時、自分の手札を1枚捨てる。",
      cost: 3,
      power: 3000,
      race: "雷人",
      card_type: "モンスター",
      is_unique: false,
    },
    "豪快迅雷 ゴロツキ": {
      effect_text: "・登場時、カードを1枚引き、手札を1枚捨てる。",
      cost: 4,
      power: 2000,
      race: "雷人",
      card_type: "モンスター",
      is_unique: false,
    },
    "爆大電磁 ドン・エレキ": {
      effect_text: "・ツインアタッカー\n・登場時、相手モンスター全てをスリープさせる。\n・自分の場に、他の「種族：雷人」が2つ以上あればこのモンスターは「能力：速攻」を持つ。",
      cost: 10,
      power: 6000,
      race: "雷人",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "見習い電導師 モーリス": {
      effect_text: "・登場時、このモンスターをエナジーに置く。その後エナジーから1枚を選び墓地に置く。",
      cost: 3,
      power: 1000,
      race: "フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "見習い電導師 シロビシン": {
      effect_text: "・このモンスターは、バトル中パワーが＋3000される。",
      cost: 5,
      power: 4000,
      race: "フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "電導師 キツネミア": {
      effect_text: "・登場時、山札の上から1枚をエナジー化する。",
      cost: 5,
      power: 2000,
      race: "フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "電導師 フェネックス": {
      effect_text: "・このモンスターが破壊されて墓地に置かれる時、代わりにエナジーになる。",
      cost: 4,
      power: 3000,
      race: "フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "一流電導師 テン・クロスタ": {
      effect_text: "・登場時、山札の上から2枚をエナジー化する。\n・このモンスターは、エナジーにある「種族：フォレスター」の枚数分パワーが＋1000される。こうしてパワーが8000を超えたら、このモンスターに「能力：ツインアタッカー」を、10000を超えたら「能力：速攻」を得る。",
      cost: 8,
      power: 4000,
      race: "フォレスター",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "稲妻小僧 ビリザキッド": {
      effect_text: "・登場時、自分または相手のシールドが4枚以下ならこのモンスターは「能力：速攻」を得る。",
      cost: 2,
      power: 1000,
      race: "雷人/スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "感電走族 パラリライダー": {
      effect_text: "・登場時、場の「種族：スピードノイザー」を選び、このターン「能力：ツインアタッカー」を与える。",
      cost: 2,
      power: 1000,
      race: "雷人/スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "ソウオンカジキ": {
      effect_text: "・速攻",
      cost: 4,
      power: 1000,
      race: "海獣/スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "炎音 紅蝶羽": {
      effect_text: "・このモンスターは、場のモンスターの数が自分の方が多い時だけ攻撃できる。",
      cost: 1,
      power: 1000,
      race: "堕虫/スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "見極める主審 デラシャウト": {
      effect_text: "・登場時、手札を1枚捨てて1枚引く。捨てたカードが「種族：スピードノイザー」ならさらにもう1枚引き手札を1枚捨てる。",
      cost: 3,
      power: 3000,
      race: "スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "暴走する前歯 マモット": {
      effect_text: "・速攻\n・登場時、自分のシールドを1枚選び手札に加える。\n・登場時、場の「種族：スピードノイザー」を破壊する。しかし相手または自分のシールドが4枚以下ならこの効果は発動しない。",
      cost: 3,
      power: 2000,
      race: "スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "爆音狂竜 ブラストザウルス": {
      effect_text: "・速攻\n・登場時、場に他の「種族：スピードノイザー」があれば「能力：ガードナー」を持つモンスターを1体選びそれを破壊する。\n・このモンスターは、場に他の「種族：スピードノイザー」があれば「能力：ツインアタッカー」を得る。\n・手札にあるこのモンスターのコストを、場の「種族：スピードノイザー」の数分減らす。",
      cost: 8,
      power: 5000,
      race: "ドラゴン/スピードノイザー",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "魂の精霊": {
      effect_text: "・登場時、カードを1枚引く\n・このモンスターは相手に選ばれず、場に自分の「種族：精霊使い」が無ければ攻撃できない。",
      cost: 3,
      power: 3000,
      race: "スピリッツ/精霊",
      card_type: "モンスター",
      is_unique: false,
    },
    "奇跡の精霊": {
      effect_text: "・登場時、山札の上から1枚をエナジー化する\n・このモンスターは相手に選ばれず、場に自分の「種族：精霊使い」が無ければ攻撃できない。",
      cost: 5,
      power: 3000,
      race: "スピリッツ/精霊",
      card_type: "モンスター",
      is_unique: false,
    },
    "精霊の伝い手 フエセプス": {
      effect_text: "・登場時、山札の上から1枚をシールドに追加する。場に他の「精霊」カードがあれば、更にもう1枚追加する。",
      cost: 9,
      power: 4000,
      race: "精霊使い",
      card_type: "モンスター",
      is_unique: false,
    },
    "精霊の守り手 ディフィシウス": {
      effect_text: "・カウンター3\n・ガードナー\n・このモンスターは攻撃できない。",
      cost: 5,
      power: 3000,
      race: "精霊使い",
      card_type: "モンスター",
      is_unique: false,
    },
    "精霊の担い手 ギセウス": {
      effect_text: "・登場時、「精霊」カード1枚を破壊してもよい。そうしたら相手は自分のモンスターを1体選び破壊する。",
      cost: 4,
      power: 3000,
      race: "精霊使い",
      card_type: "モンスター",
      is_unique: false,
    },
    "精霊神話「第1章―光あれ」": {
      effect_text: "・山札の上から2枚を表向きにする。その中から「種族：精霊」を全て手札に加え、残りを好きな順で山札の下に戻す。",
      cost: 2,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "精霊神 ファーザーズ・ゼウス": {
      effect_text: "・ツインアタッカー\n・手札にあるこのカードのコストは場の「精霊」カードの数だけ少なくなる。\n・登場時、相手は次ターンの終了時まで魔法カードを使うことが出来ない。",
      cost: 10,
      power: 7000,
      race: "神",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "破壊砲牙龍 ディクラスター・ドラゴン": {
      effect_text: "・速攻\n・ツインアタッカー\n・登場時、お互いはシールドを1枚手札に加える。",
      cost: 10,
      power: 9000,
      race: "ドラゴン/改造龍機",
      card_type: "エボルモンスター",
      is_unique: true,
    },
    "大爆発": {
      effect_text: "・カウンター7\n・場のモンスター全てを破壊する",
      cost: 13,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "秘術師 フィーデン・ニトロ": {
      effect_text: "・自分のターン開始時、このモンスターを破壊する。そのあとモンスターが出るまで自分の山札をめくり、それを場に出す。",
      cost: 5,
      power: 1000,
      race: "悪魔/マジシャン",
      card_type: "モンスター",
      is_unique: true,
    },
    "剛弾 ファウスト・ガントレット": {
      effect_text: "・フラッシュカウンター\n・場の相手カード1枚を破壊する",
      cost: 4,
      power: null,
      race: "装具",
      card_type: "装備",
      is_unique: true,
    },
    "閉ざされし暗黒の扉": {
      effect_text: "・このモンスターは攻撃できない。\n・自分のターン開始時、このモンスターを破壊する。そのあとカードを5枚引き、手札からコストが8以下の「種族：悪魔」を場に出す。",
      cost: 13,
      power: 6666,
      race: "悪魔",
      card_type: "モンスター",
      is_unique: true,
    },
    "戦闘準備": {
      effect_text: "・山札の上から5枚を見て「カードタイプ：装備」を1枚相手に見せてから手札に加える。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "墓掘り名人のスゴワザ": {
      effect_text: "・カウンター5\n・エナジーから好きな数を墓地に置き、その枚数と同じだけ山札の上から墓地に置く。",
      cost: 7,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "公正な宝箱": {
      effect_text: "・相手はカードを1枚引いてもよい。その後自分はカードを3枚引く",
      cost: 5,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "大いなる渦潮": {
      effect_text: "・カウンター4\n・お互いは自分のモンスターを1体選び手札に戻す。",
      cost: 5,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "歴戦の達人 ヘロス＝バロン3世": {
      effect_text: "・登場時、手札からコストが5以下の「カードタイプ：装備」を場に出しこのモンスターに装備する。\n・攻撃時、場の「種族：武器」をこのモンスターに装備させてもよい。",
      cost: 5,
      power: 4000,
      race: "戦士/英雄",
      card_type: "モンスター",
      is_unique: false,
    },
    "魔法見習い サポレス": {
      effect_text: "・手札の「カードタイプ：装備」のコストは１少なくなる。",
      cost: 3,
      power: 2000,
      race: "魔法使い",
      card_type: "モンスター",
      is_unique: false,
    },
    "火吹き獣 フレブラス": {
      effect_text: "・カウンター2\n・登場時、パワーが2000以下の相手モンスターを1体選び破壊する。",
      cost: 5,
      power: 3000,
      race: "モンストロ/フレイマー",
      card_type: "モンスター",
      is_unique: false,
    },
    "冥界の呪杖": {
      effect_text: "・登場時、自分の墓地からコスト5以下のカードを選び場に出す。\n・このカードを装備したモンスターが場にいる限り、このカードの効果で場に出たカードは場を離れない。\n・装備モンスターが場を離れた時、このカードは墓地に置かれる。",
      cost: 7,
      power: null,
      race: "杖/呪物",
      card_type: "装備",
      is_unique: false,
    },
    "聖剣 アス・カリュード": {
      effect_text: "・装備モンスターは、「能力：ツインアタッカー」を得る。",
      cost: 3,
      power: null,
      race: "剣/武器/神器",
      card_type: "装備",
      is_unique: false,
    },
    "木刀": {
      effect_text: "・装備モンスターは、バトル中パワーが3000上がる。",
      cost: 2,
      power: null,
      race: "剣/武器",
      card_type: "装備",
      is_unique: false,
    },
    "荘厳な大盾": {
      effect_text: "・カウンター3\n・装備モンスターは、「能力：ガードナー」を得る。",
      cost: 6,
      power: null,
      race: "盾/防具",
      card_type: "装備",
      is_unique: false,
    },
    "ヘビー・ネックレス": {
      effect_text: "・装備モンスターは攻撃できない。\n・これを装備したモンスターのいるプレイヤーは自分のターン開始時にカードを1枚引いてもよい。その後、そのプレイヤーは2エナジーを使ってこの装備を外してもよい。",
      cost: 5,
      power: null,
      race: "アクセサリー",
      card_type: "装備",
      is_unique: false,
    },
    "S-5 速写のデジィカメ": {
      effect_text: "・ガードナー\n・攻撃終了時、このモンスターを破壊する。",
      cost: 2,
      power: 1000,
      race: "スクラップ・マシーン/スピードノイザー",
      card_type: "モンスター",
      is_unique: false,
    },
    "S-4 モバージュ": {
      effect_text: "・フラッシュカウンター\n・自分の「種族：スクラップ・マシーン」が破壊された時、カードを1枚引く。",
      cost: 3,
      power: 1000,
      race: "スクラップ・マシーン",
      card_type: "モンスター",
      is_unique: false,
    },
    "M-8 ネッパー・オーブナー": {
      effect_text: "・攻撃時、場にある自分の「種族：スクラップ・マシーン」を1枚選び破壊してもよい。そうしたら、このモンスターはこのターン「能力：ツインアタッカー」を得る。",
      cost: 4,
      power: 5000,
      race: "スクラップ・マシーン",
      card_type: "モンスター",
      is_unique: false,
    },
    "M-3 バクスタード・ライアー": {
      effect_text: "・登場時、場の「種族：スクラップ・マシーン」を1枚選んでもよい。そうしたら、相手は自身の場のカードを2枚選ぶ。それらを全て破壊する。",
      cost: 7,
      power: 5000,
      race: "スクラップ・マシーン",
      card_type: "モンスター",
      is_unique: false,
    },
    "L-2 冷壊機甲 クラッシュアス・パンクーラチオン": {
      effect_text: "・ツインアタッカー\n・登場時、自分の場のモンスターを好きな数破壊してもよい。\n・自分の他の「種族：スクラップ・マシーン」が破壊された時、相手のシールドを1枚選びブレイクする。",
      cost: 8,
      power: 7000,
      race: "スクラップ・マシーン",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "秀逸なる旋律(メロディ) レディ・トゥ・シューズ": {
      effect_text: "・アームズアップ：バレジェンヌ\n・装備モンスターのパワーは2000上がる。\n・装備モンスターが「種族：バレジェンヌ」であり、このターン中に場に出ていれば「能力：リブートアタッカー」を得る。(この効果は1ターンに1度しか発動しない。)",
      cost: 4,
      power: null,
      race: "精霊/装具",
      card_type: "装備",
      is_unique: false,
    },
    "卓抜たる律動(リズム) レディ・チュール・ペチコート": {
      effect_text: "・アームズアップ：バレジェンヌ\n・装備モンスターが攻撃する時、カードを1枚引く。",
      cost: 2,
      power: null,
      race: "精霊/装具",
      card_type: "装備",
      is_unique: false,
    },
    "流麗なる前奏曲(プレリュード) アン・ヌ・ダルク": {
      effect_text: "・速攻\n・場に「種族：装具」を持つ装備がある時、手札にあるこのモンスターのコストを2少なくする。",
      cost: 5,
      power: 1000,
      race: "精霊使い/バレジェンヌ",
      card_type: "モンスター",
      is_unique: false,
    },
    "婉然たる行進曲(マーチ) ドゥ・エリザべート": {
      effect_text: "・自分の「種族：バレジェンヌ」が攻撃をした時、それがこのターン2回目の攻撃でこのカードが手札にあるなら、このカードを捨ててもよい。そうしたら、エナジー1枚を使って、場のモンスターを1体選びリブートさせる。(ただしこのモンスターの同じ効果は1ターンに1度しか使えない)",
      cost: 7,
      power: 6000,
      race: "精霊使い/バレジェンヌ",
      card_type: "モンスター",
      is_unique: false,
    },
    "優艷なる後奏曲(ポストリュード) トロワ・エルキューレ": {
      effect_text: "・自分の「種族：バレジェンヌ」が攻撃をした時、それがこのターン3回目の攻撃でこのカードが手札にあるなら、このカードを相手に見せてもよい。そうしたら、その攻撃の終わりに、このモンスターをエナジー2枚を使って場に出す。(ただしこのモンスターの同じ効果は1ターンに1度しか使えない)\n・速攻\n・登場時、相手モンスターを1体選びリブートさせる。",
      cost: 8,
      power: 4000,
      race: "精霊使い/バレジェンヌ",
      card_type: "モンスター",
      is_unique: false,
    },
    "嬋媛なる協奏曲(コンチェルト) ヴェルセイユ・ローゼ": {
      effect_text: "・自分の「種族：バレジェンヌ」が攻撃をした時、それがこのターン2回目の攻撃でこのカードが手札にあるなら、このカードを捨ててもよい。そうしたらカードを2枚引く。(ただしこのモンスターの同じ効果は1ターンに1度しか使えない)\n・登場時、手札から「カードタイプ：装備」を1枚場に出してもよい。",
      cost: 6,
      power: 4000,
      race: "精霊使い/バレジェンヌ",
      card_type: "モンスター",
      is_unique: false,
    },
    "忠実なる骨獣 スカルベロス": {
      effect_text: "・このカードが場から墓地へ送られた時、手札から「種族：悪魔」を捨てる。そうしたらこのカードを手札に戻す。\n・登場時、相手の手札を1枚見ないで選び、それを捨てさせる。",
      cost: 4,
      power: 2000,
      race: "悪魔/魔獣",
      card_type: "モンスター",
      is_unique: false,
    },
    "デビルズ・トレード": {
      effect_text: "・カウンター4\n・手札を1枚捨てる。そうしたら、次の内から1つ選び、それをこのカードの能力として使用する。ただし、その捨てたカードが「種族：悪魔」なら、次の内からどちらもこのカードの能力として使用する。\n▶場のカードを1枚破壊する。\n▶墓地からカードを1枚手札に加える",
      cost: 6,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "悪魔を呼ぶ宝箱": {
      effect_text: "・カウンター4\n・カードを2枚引き、手札を1枚捨てる。そのカードが「種族：悪魔」ならそのカードを手札に戻す。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "魔王の鉄兜(ファウスト・オブ・ヘルム)": {
      effect_text: "・アームズアップ：悪魔\n・このカードを装備しているモンスターが場を離れる時、代わりに手札を1枚捨てる。(この効果は1ターンにつき1度しか使えない。)",
      cost: 6,
      power: null,
      race: "悪魔/防具",
      card_type: "装備",
      is_unique: false,
    },
    "魔王の大鎌(ファウスト・オブ・デスサイズ)": {
      effect_text: "・アームズアップ：悪魔\n・装備モンスターがいる限り、自分の悪魔族はパワーが3000上がる。\n・このカードが手札から捨てられた時、今が相手ターンならコストが13の「種族：悪魔」を墓地から場に出してもよい。(この効果は1ターンにつき1度しか使えない。)",
      cost: 4,
      power: null,
      race: "悪魔/武器",
      card_type: "装備",
      is_unique: false,
    },
    "暗黒の扉を護る者 バアル＝ファントム": {
      effect_text: "・ツインアタッカー\n・ガードナー\n・登場時、手札から「種族：悪魔」を1枚捨ててもよい。そうしたら山札の上から3枚を墓地に置く。\n・攻撃時、墓地から「種族：悪魔」を1枚選び、場に出してもよい。",
      cost: 13,
      power: 6000,
      race: "悪魔",
      card_type: "モンスター",
      is_unique: false,
    },
    "悪魔王 ファウスト": {
      effect_text: "・ツインアタッカー\n・登場時、手札から「種族：悪魔」を2枚まで捨ててもよい。その数分、相手モンスターを選び破壊する。\n・このモンスターが装備している時、場のモンスターは全て「能力：速攻」を得る。",
      cost: 8,
      power: 7000,
      race: "悪魔/魔族王",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "ビースト・リベレイション": {
      effect_text: "・このカードのコストは自分の場のモンスターの数分多くなる。\n・場の自分のモンスター全てはこのターンパワーが5000上がり、「能力：ツインアタッカー」を得る。",
      cost: 2,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "虐天の大剣 ルミナス・カリバー": {
      effect_text: "・装備モンスターはパワーが4000上がりリブート状態のモンスターを攻撃できる。\n・自分のモンスターがバトルした時、そのモンスターに「能力：リブートアタッカー」を与える。\n・自分のシールドが2枚以下の時、このカードを装備させるコストは2になる。",
      cost: 10,
      power: null,
      race: "剣/武器/神器",
      card_type: "装備",
      is_unique: true,
    },
    "呪悪の首飾り(アブダクト・ペンダント)": {
      effect_text: "・装備モンスターのパワーは1000になり、「能力：アタッカー」の効果は無くなる。\n・装備モンスターが場を離れた時、このカードは墓地に置かれる。",
      cost: 1,
      power: null,
      race: "アクセサリー/呪物/悪魔",
      card_type: "装備",
      is_unique: true,
    },
    "スーパーエナジスト エナ爺": {
      effect_text: "・登場時、墓地のカードを3枚までエナジーにする。しかし、このターンそれらのエナジーは使えない。",
      cost: 4,
      power: 4000,
      race: "フォレスター/仙人",
      card_type: "モンスター",
      is_unique: false,
    },
    "時を渡る宝箱": {
      effect_text: "・このカードを使った後、墓地に置く代わりに山札の上から3枚目に置く。こうしてこの効果を使った後に「カード名：時を渡る宝箱」が山札からエナジーとなった時1度だけ、カードを5枚引く。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "悪魔 藤蝶羽": {
      effect_text: "・登場時、自分の手札を1枚捨てる。\n・場を離れた時、相手に自分の手札を1枚選ばせる。自分はそれを捨てる。",
      cost: 1,
      power: 1000,
      race: "悪魔/堕虫",
      card_type: "モンスター",
      is_unique: false,
    },
    "電導師 シカルバ": {
      effect_text: "・このモンスターを召喚する時、エナジーにある｢種族：フォレスター｣はエナジー2枚分になる。\n・登場時、相手モンスターを1体選び破壊する。",
      cost: 9,
      power: 5000,
      race: "フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "運命の精霊 ディスティー": {
      effect_text: "・攻撃時、カードを1枚引き手札にあるコスト5以下の「精霊」カードであり、かつ「種族：スピリット」を場に出してもよい。\n・このモンスターは相手に選ばれず、場に自分の「種族：精霊使い」が無ければ攻撃できない。",
      cost: 5,
      power: 6000,
      race: "スピリッツ/精霊",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "熱狂騒大 ノイズ＝ザ・ライブ": {
      effect_text: "・フラッシュカウンター\n・自分の墓地にある「種族：スピードノイザー」を2枚まで手札に加えてもよい。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "比類なき和音(ハーモニー) レディ・ボン・バレラ": {
      effect_text: "・このカードを装備したモンスターが離れる時、かわりにこのカードを墓地に破壊してもよい。そうしたらそのモンスターは手札に戻る。\n・このカードが装備されている間、自分は自身のメインステップ以外で使用するエナジーが1減る。(この効果によってカウンターのコストは軽減されない。)\n・アームズアップ：バレジェンヌ",
      cost: 3,
      power: null,
      race: "装具/精霊",
      card_type: "装備",
      is_unique: false,
    },
    "エナジーホール": {
      effect_text: "・自分のエナジーから2枚を選び墓地に置き相手モンスターを1体選び山札の下に送る。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "ハジけるアイドル ピーチソーダ": {
      effect_text: "・このモンスターが破壊された時、カードを1枚引く。それが自分のターンであれば更にもう1枚引く。",
      cost: 3,
      power: 1000,
      race: "アイドル",
      card_type: "モンスター",
      is_unique: false,
    },
    "剣残 ティファ・リリア": {
      effect_text: "・カウンター3\n・登場時、コスト5以下のモンスターを1体選び破壊する。",
      cost: 5,
      power: 4000,
      race: "戦士",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "巌壁の土進兵": {
      effect_text: "・ガードナー",
      cost: 5,
      power: 6000,
      race: "虚兵/ゴーレム",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "ヘルメシアのスピードシューズ": {
      effect_text: "・装備モンスターは「能力：速攻」を得る。",
      cost: 4,
      power: null,
      race: "装具/神器",
      card_type: "装備",
      is_unique: false,
    },
    "リバイバル・リサイタル": {
      effect_text: "・カウンター5\n・自分の墓地にあるコストが3以下のモンスターを3体まで選び、場に出す。",
      cost: 9,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "Aリアン グレイ": {
      effect_text: "・このカードは墓地から召喚出来る。そしてこのモンスターは手札からは召喚することが出来ない。\n・登場時、手札を1枚捨て、相手モンスターを2体選び破壊する。\n・このモンスターは場を離れる時、山札の下に置かれる。\n・エボルシナジー：ツインアタッカー、ガードナー",
      cost: 8,
      power: 6000,
      race: "ギャラクシアン",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "巨悪昆虫 篦玖䋱寿王兜(ヘラクレスオオカブト)": {
      effect_text: "・ツインアタッカー\n・登場時、場にある他の｢カードタイプ：エボルモンスター｣を1体選んでもよい。そのモンスターはこのターン｢能力：エボルシナジー｣は条件を満たしていなくても使用でき、かつその効果は2回発動する。\n・エボルシナジー：攻撃時、墓地から｢種族：堕虫｣を1枚選び手札に加える。そうしたら相手モンスターを1体破壊する。",
      cost: 7,
      power: 6000,
      race: "堕虫/皇帝種",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "絶景 夜営蛍(ヤエイホタル)": {
      effect_text: "・相手ターン中、このモンスターは選ばれない。",
      cost: 2,
      power: 1000,
      race: "堕虫",
      card_type: "モンスター",
      is_unique: false,
    },
    "戒律 闇蜘蛛(ヤミクモ)": {
      effect_text: "・このモンスターが破壊された時、相手は自身の手札を1枚選びそれを捨てる。",
      cost: 3,
      power: 2000,
      race: "堕虫",
      card_type: "モンスター",
      is_unique: false,
    },
    "武人 緋鎌斬(アカカマキリ)": {
      effect_text: "・このモンスターは相手プレイヤーに攻撃できない。\n・登場時、相手モンスター1体を選んでもよい。そのモンスターとバトルする。\n・バトル勝利時、墓地の｢種族：堕虫｣を1枚手札に加える。",
      cost: 4,
      power: 4000,
      race: "堕虫",
      card_type: "モンスター",
      is_unique: false,
    },
    "伽藍堂 棟梁飛蝗(トウリョウバッタ)": {
      effect_text: "・登場時、相手のコスト3以下のモンスターを1体選び破壊する。\n・エボルシナジー：攻撃時、カードを2枚引く。",
      cost: 6,
      power: 5000,
      race: "堕虫",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "加速 金蜻蜓(キンヤンマ)": {
      effect_text: "・エボルシナジー：攻撃時、自分の場の他モンスター1体を選びリブートさせる。",
      cost: 5,
      power: 2000,
      race: "堕虫",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "集益 千虫理威(センチュリー)": {
      effect_text: "・エナジーにある｢種族：堕虫｣の数だけ山札の上から表向きにする。その中から｢カードタイプ：モンスター｣を1枚選び相手に見せてから手札に加える。それ以外を全て好きな順序で山札の下に置く。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "テラ・ティラノ": {
      effect_text: "・速攻",
      cost: 5,
      power: 1000,
      race: "ダイノガン/古代兵器",
      card_type: "モンスター",
      is_unique: false,
    },
    "プテラ・プドン": {
      effect_text: "・登場時、相手のパワー3000以下のモンスターを1体選び破壊する。",
      cost: 5,
      power: 2000,
      race: "ダイノガン/古代兵器",
      card_type: "モンスター",
      is_unique: false,
    },
    "トラセラ・トリケラ": {
      effect_text: "・ガードナー\n・このモンスターは相手プレイヤーに攻撃出来ない。",
      cost: 5,
      power: 2000,
      race: "ダイノガン/古代兵器",
      card_type: "モンスター",
      is_unique: false,
    },
    "ダイ戦士 ティライガーZ": {
      effect_text: "・自分の「種族：ダイノガン」の攻撃終了時、手札を2枚捨ててもよい。このカードを手札から召喚してもよい。\n・エボルシナジー：登場時、墓地のコスト5以下の「種族：ダイノガン」を1枚選びそれを場に出す。",
      cost: 7,
      power: 4000,
      race: "ダイノガン/古代兵器",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "ダイ剣士 プテラオン": {
      effect_text: "・自分の「種族：ダイノガン」の登場時、手札を2枚捨ててもよい。このカードを手札から召喚してもよい。\n・エボルシナジー：登場時、カードを2枚引く。",
      cost: 7,
      power: 3500,
      race: "ダイノガン/古代兵器",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "ダイ盾士 トリケムズ": {
      effect_text: "・自分の「種族：ダイノガン」のバトル時、手札を2枚捨ててもよい。このカードを手札から召喚してもよい。\n・エボルシナジー：自分のモンスターがバトルする時、かわりにこのモンスターとバトルさせてもよい。",
      cost: 7,
      power: 6000,
      race: "ダイノガン/古代兵器",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "竜伝承のグリモア": {
      effect_text: "・登場時、手札から「種族：ドラゴンテイマー」を1枚選び場に出してもよい。そのあと手札を全て山札の下に好きな順序で戻す。",
      cost: 5,
      power: 4000,
      race: "ドラゴンテイマー",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "竜呼びの杖": {
      effect_text: "・登場時、またはこのカードを装備したモンスターの攻撃時、山札の上から1枚を表向きにしてそのカードが「種族：ドラゴン」なら場に出す。それ以外なら手札に加える。また、このカードを装備するモンスターが「種族：ドラゴンテイマー」ならこの効果はもう一度発動する。",
      cost: 7,
      power: null,
      race: "杖/ドラゴンテイマー",
      card_type: "装備",
      is_unique: false,
    },
    "砲大我竜 キャノークス・ドラゴン": {
      effect_text: "・速攻\n・ツインアタッカー\n・登場時、このターン中「このモンスターは相手モンスターに向かって攻撃出来ず攻撃先は変更されない。」を得る。",
      cost: 9,
      power: 6000,
      race: "ドラゴン/改造龍機",
      card_type: "モンスター",
      is_unique: false,
    },
    "弾丸 バレドラン": {
      effect_text: "・登場時、このモンスターを破壊してもよい。\n・このモンスターが破壊された時、自分モンスターを1体選びリブートさせる。",
      cost: 4,
      power: 3000,
      race: "ドラゴン/改造龍機",
      card_type: "モンスター",
      is_unique: false,
    },
    "竜潜術": {
      effect_text: "・自分のエナジーを1枚選び山札の上に置く。",
      cost: 1,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "不死鳥の羽": {
      effect_text: "・装備モンスターが場を離れた時、このカードを墓地に置いてもよい。そうしたらそのモンスターを墓地から場に出す。\n・自分のターン開始時、このカードが墓地にあれば自分の手札を2枚捨ててもよい。そうしたらこのカードを手札に戻す。",
      cost: 4,
      power: null,
      race: "アクセサリー/神獣",
      card_type: "装備",
      is_unique: true,
    },
    "最速神 ヘルメシア": {
      effect_text: "・速攻",
      cost: 1,
      power: 500,
      race: "神",
      card_type: "モンスター",
      is_unique: true,
    },
    "伝説の勇者 ヘロス＝バロン1世": {
      effect_text: "・登場時、カードを2枚引く。\n・手札の「カードタイプ：装備」のコストは1になる。",
      cost: 5,
      power: 4000,
      race: "勇者/戦士",
      card_type: "モンスター",
      is_unique: true,
    },
    "反撃の剛霊機兵": {
      effect_text: "・このモンスターは相手モンスターにしか攻撃できない。",
      cost: 3,
      power: 15000,
      race: "虚兵/ゴーレム",
      card_type: "モンスター",
      is_unique: true,
    },
    "掴め！ビッグドリーム・JACKPOT": {
      effect_text: "・お互いのプレイヤーはそれぞれ1～7までの数字を1つずつ選ぶ。そのあとお互いは山札の下をめくる。こうして相手の山札のカードと同じコストを選んだプレイヤーはそのコストと同じ数カードを引く。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "欲望の精霊 眠れる森のオー・ローラ": {
      effect_text: "・このモンスターはリブート状態で場に出る。\n・エボルシナジー：登場時、このモンスターをリブートする。\n・このモンスターのリブート時、相手モンスターを1体選びスリープさせる。\n・このモンスターは相手に選ばれず、場に自分の「種族：精霊使い」が無ければ攻撃できない。\n・リブートアタッカー",
      cost: 8,
      power: 5000,
      race: "精霊/メルヘン",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "城将機竜 トルネイド・フォトン・ドラゴン": {
      effect_text: "・登場時、相手モンスター2体を手札に戻す。\n・ツインアタッカー",
      cost: 8,
      power: 4000,
      race: "ドラゴン/改造龍機",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "ヴェロキ・ヴェプトル": {
      effect_text: "・リブートアタッカー",
      cost: 5,
      power: 2000,
      race: "ダイノガン/古代兵器",
      card_type: "モンスター",
      is_unique: false,
    },
    "ダイ銃士 ヴェロキレイバー": {
      effect_text: "・自分の「種族：ダイノガン」のリブート時、このカードを手札から3コストで召喚してもよい。\n・エボルシナジー：自分モンスターの攻撃時、そのモンスターをリブートさせる。(この効果は1ターンに1度まで発動する。)",
      cost: 7,
      power: 3000,
      race: "ダイノガン/古代兵器",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "大切断": {
      effect_text: "・カウンター6\n・パワー5000以下のモンスターを全て破壊する。",
      cost: 8,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "閃光": {
      effect_text: "・フラッシュカウンター\n・相手モンスターを1体選びスリープさせる。",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "魔鍵の宝箱": {
      effect_text: "・手札を1枚捨て1枚引く。捨てたカードが｢カードタイプ：魔法｣であればさらにもう1枚引く。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "モンスター・ゲート": {
      effect_text: "・手札を1枚捨てる。その後、山札を確認しモンスター1枚を選び相手に見せてからそれを手札に加える。",
      cost: 6,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "拳華屋 ストレイト": {
      effect_text: "・登場時、相手モンスターを1体選び破壊する。その後相手のシールドを1枚ブレイクする。\n・エボルシナジー：ツインアタッカー",
      cost: 5,
      power: 1000,
      race: "スピードノイザー",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "双剣からなる者": {
      effect_text: "・リブートアタッカー",
      cost: 4,
      power: 2000,
      race: "戦士",
      card_type: "モンスター",
      is_unique: false,
    },
    "ヒノボール": {
      effect_text: "・カウンター2\n・ファイトアタッカー\n・このモンスターは相手プレイヤーを攻撃できない。",
      cost: 3,
      power: 3000,
      race: "モンストロ/フレイマー",
      card_type: "モンスター",
      is_unique: false,
    },
    "アドアリアの夜": {
      effect_text: "・自分のエナジーが7枚以上あり、それらがそれぞれ違う種族を持っていたならその枚数だけ手札にあるこのカードのコストは少なくなる。\n・登場時または自分のターン開始時、山札から3枚を表向きにする。それらが全て｢カードタイプ：モンスター｣であり、それぞれ違う種族を持っていたなら、場にある☆の効果を使用する。残りは山札の下に好きな順序で戻す。\n☆自分の場にあるカードの種族を数える。相手は次の自身のターン終了時まで、その枚数分、使用するカードの効果を無視する。(自分は同名の他カードを含めたこの効果をゲーム中1度しか使用できない。)",
      cost: 8,
      power: null,
      race: null,
      card_type: "フィールド",
      is_unique: false,
    },
    "炎剣の使い エンラスト・フレア": {
      effect_text: "・登場時、山札の上から5枚を表向きにする。それらが全て｢カードタイプ：モンスター｣であり、それぞれ違う種族を持っていたならそれらの中から1枚を手札に加え、場にある☆の効果を使用する。残りは山札の下に好きな順序で戻す。\n☆自分モンスター1体を選ぶ。それはこのターン｢能力：速攻、ツインアタッカー｣を得る。",
      cost: 3,
      power: 2000,
      race: "エンジェント/フレイマー",
      card_type: "モンスター",
      is_unique: false,
    },
    "水銃の使い スイート・ワタソン": {
      effect_text: "・登場時、山札の上から5枚を表向きにする。それらが全て｢カードタイプ：モンスター｣であり、それぞれ違う種族を持っていたならそれらの中から1枚を手札に加え、場にある☆の効果を使用する。残りは山札の下に好きな順序で戻す。\n☆カードを2枚引く。",
      cost: 3,
      power: 2000,
      race: "エンジェント/水簾",
      card_type: "モンスター",
      is_unique: false,
    },
    "森鎚の使い フォルス・キリマイヤ": {
      effect_text: "・登場時、山札の上から5枚を表向きにする。それらが全て｢カードタイプ：モンスター｣であり、それぞれ違う種族を持っていたならそれらの中から1枚を手札に加え、場にある☆の効果を使用する。残りは山札の下に好きな順序で戻す。\n☆山札の上から2枚をエナジー化する。",
      cost: 5,
      power: 3000,
      race: "エンジェント/フォレスター",
      card_type: "モンスター",
      is_unique: false,
    },
    "魔拳の使い マジガン・バクラシュ": {
      effect_text: "・カウンター3\n・登場時、山札の上から5枚を表向きにする。それらが全て｢カードタイプ：モンスター｣であり、それぞれ違う種族を持っていたならそれらの中から1枚を手札に加え、場にある☆の効果を使用する。残りは山札の下に好きな順序で戻す。\n☆手札を1枚捨て、相手モンスターを1体選び破壊する。",
      cost: 4,
      power: 3000,
      race: "エンジェント/悪魔",
      card_type: "モンスター",
      is_unique: false,
    },
    "もちむにの果実": {
      effect_text: "・このカードが手札にある時、このカードを捨てても良い。そうしたらこのターン、次に使用する「もち」または「むに」カードのコストを3減らす。ただしコストは1より小さくならない。",
      cost: 0,
      power: null,
      race: null,
      card_type: "マテリアル",
      is_unique: false,
    },
    "もちもちばーん": {
      effect_text: "・山札の上から3枚を見る。その中から名前の異なる「もち」または「むに」カードを最大2枚まで場に出す。このようにして場に出したカードのコストの合計以下のコストを持つ相手モンスターを1体選び破壊する。残りは好きな順序で山札の下に置く。",
      cost: 12,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "うさもちぃ": {
      effect_text: "・登場時、山札から2枚を表向きにする。その中の「種族：メルヘン」を好きな数手札に加える。",
      cost: 5,
      power: 2500,
      race: "メルヘン",
      card_type: "モンスター",
      is_unique: false,
    },
    "むにかめ": {
      effect_text: "・登場時、墓地にある「もち」または「むに」カードを1枚選び手札に加える。",
      cost: 5,
      power: 1500,
      race: "メルヘン",
      card_type: "モンスター",
      is_unique: false,
    },
    "ありもち": {
      effect_text: "・攻撃時、他のモンスター1体に「能力：速攻」を与える。",
      cost: 7,
      power: 3500,
      race: "メルヘン",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "きりむにす": {
      effect_text: "・ガードナー\n・攻撃時、墓地のカード1枚を選び手札に加える。",
      cost: 6,
      power: 3500,
      race: "メルヘン",
      card_type: "エボルモンスター",
      is_unique: false,
    },
    "もちぃぬ": {
      effect_text: "・登場時、山札の上から1枚をエナジー化する。",
      cost: 6,
      power: 2500,
      race: "メルヘン",
      card_type: "モンスター",
      is_unique: false,
    },
    "稲光釣人 \"釣り'ザキッド": {
      effect_text: "・登場時、手札の「種族：魚」を相手に見せてもよい。そのカードを山札に加えシャッフルし、カードを1枚引く。\n・自分の「釣り竿」カードの使用コストを1減らす。",
      cost: 2,
      power: 1000,
      race: "雷人",
      card_type: "モンスター",
      is_unique: false,
    },
    "イナビカリ釣具店": {
      effect_text: "・山札から4枚を見て「釣り」カードを1枚相手に見せてから手札に加えてもよい。こうして手札に加えた場合、残りを山札の上に、そうでないなら山札の下に好きな順に戻す。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "光印の釣り竿": {
      effect_text: "・登場時、自分は3枚引き、同じ枚数を手札から山札の上へ好きな順に戻す。\n・場にコスト6以上の「種族：魚」が出た時、このカードを破壊する。",
      cost: 3,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "電撃機能付き釣り竿": {
      effect_text: "・フラッシュカウンター\n・登場時、相手モンスターを1体選ぶ。次ターンの終了時までそのモンスターに行動不能を与える。\n・場にコスト6以上の「種族：魚」が出た時、このカードを破壊する。",
      cost: 6,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "気合いのイナズマ1本釣り": {
      effect_text: "・カードを1枚引き、手札からコスト3以下の「種族：魚もしくは雷人」を1体場に出す。\n・自分のターン初めのドローをした時、このカードが墓地にあり場に「釣り竿」カードがあれば、場の「種族：魚もしくは雷人」を好きな数破壊してもよい。そうしたら山札を5枚を見て、その中から破壊したカードのコスト合計以下のコストを持つ「種族：魚」モンスターを場に出す。(この効果は1ターンにつき1度しか使えない。)",
      cost: 4,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: false,
    },
    "マミレシラス": {
      effect_text: "・自分のコストが5以上の｢種族：魚｣は｢能力：速攻｣を得る。",
      cost: 3,
      power: 1000,
      race: "魚",
      card_type: "モンスター",
      is_unique: false,
    },
    "豊作魚 イレグイマグロ": {
      effect_text: "・ツインアタッカー\n・攻撃時、山札の上から1枚目をめくりそれが｢種族：魚｣であれば場に出してもよい。",
      cost: 7,
      power: 5000,
      race: "魚",
      card_type: "モンスター",
      is_unique: false,
    },
    "マジック・ディストラクション": {
      effect_text: "・山札の上から｢カードタイプ：モンスター｣が出るまで、もしくは中止するまで表向きにする。こうして表向きにしたカードの枚数だけ相手シールドをブレイクする。",
      cost: 7,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "爆弾": {
      effect_text: "・このカードをターン初めのドローで引いた時、表向きにしてもよい。そうしたらお互いの場のカードを全て破壊する。その後、このカードと自分の手札を全て墓地に置く。",
      cost: 100,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "大神海 リヴァイ・アサシン": {
      effect_text: "・ツインアタッカー\n・登場時、自分のエナジーを好きな数墓地に置いてもよい。その数になるように相手モンスターを破壊する。そのときその数に足りなかった場合、その数になるように相手の手札を見ないで選び捨てさせる。",
      cost: 13,
      power: 10000,
      race: "魚/神獣",
      card_type: "モンスター",
      is_unique: true,
    },
    "リスタート": {
      effect_text: "・お互いのプレイヤーは手札を全て捨てる。",
      cost: 10,
      power: null,
      race: null,
      card_type: "呪文",
      is_unique: true,
    },
    "決して堕ちぬ城塞 チェリブロス・ファミリア": {
      effect_text: "・相手が攻撃をする時、攻撃しているそれ以外のカードを1枚破壊する。\n・相手モンスターが破壊された時、それがこのターン3回目に破壊された相手カードであればこのカードを破壊する。\n・このカードが破壊された時、相手は手札を自身で2枚選び捨てる。",
      cost: 5,
      power: null,
      race: null,
      card_type: "フィールド",
      is_unique: true,
    },
};

export function applyCardInfoOverrides<C extends Card>(card: C): C {
  const o = CARD_INFO_OVERRIDES[card.name];
  if (!o) return card;
  return { ...card, ...o };
}
